### ISSUE TITLE
Things to do milestone 2

### ISSUE THREAD

**Issue by AndresPitta** [UBC-MDS/DSCI_522_Group-308_Used-Cars#12]
Hey @pokrovskyy and @bradentam ,

Here is a checklist on the things to do for this milestone:

- [x]  **Script 1:** Download/Save data script - Improve base on feedback given by the TA 

Andrés:
- [x]  **Script 2:** Data wrangling/prepreprocessing script. 
                   **Arguments:**
                               - Raw data path
                               - Cleaned data path
                               - Test/train

Braden:
- [x]  **Script 3:** EDA again.
                   **Arguments:**
                               - Cleaned data path
                               - results.png

Serg:
- [x]  **Script 4:** ML algorithm
                   **Arguments:**
                               - Cleaned data path
                               - Results

**Markdown Script - Report**
- [x] introduction/justification of question - Braden
- [x] introduces the data set - Braden
- [x] presents the findings/results - Serg
- [x] interprets the findings/results in context of the question - Serg
- [x] Some critique of the analysis is also expected (limitations, assumptions, etc) - Serg
- [x] statement of future directions - Braden
- [x] 2 references (including the data source) and citing the packages - Andres

Proposal
- [x] implement feedback - Braden

Andres - update readme 
- [x] usage (which order scripts are run in, what expected inputs are) 
- [x] dependency flow chart

**Comment by AndresPitta** [comment]
Hey guys, 

I just created a pull request with the data wrangling script.

these are the parameters it takes:
Options:

--DATA_FILE_PATH=<DATA_FILE_PATH>  Path (including filename) to retrieve the csv file. [default: ../data/vehicles.csv]
--TRAIN_FILE_PATH=<TRAIN_FILE_PATH>  Path (including filename) to print the train portion as a csv file. [default: ../data/vehicles_train.csv]
--TEST_FILE_PATH=<TEST_FILE_PATH>  Path (including filename) to print the test portion as a csv file. [default: ../data/vehicles_test.csv]
--TARGET=<TARGET> Name of the response variable to use. [default: price]
--REMOVE_OUTLIERS=<REMOVE_OUTLIERS> Logical value that takes YES as value if the outliers should be removed, NO otherwise. [default: YES]
--TRAIN_SIZE=<TRAIN_SIZE> Decimal value for the train/test split. [default: 0.9] 

What I did was removing prices over the 99th percentile, fixing the NAs for the categorical variables and splitting the train/test set. Every other variable seemed to be ok, based on the EDA.

Also, I haven't done the references for the libraries I used.
Please, tell me what you think,
