### ISSUE TITLE
Milestone 3 Tasks

### ISSUE THREAD

**Issue by pokrovskyy** [UBC-MDS/DSCI_522_Group-308_Used-Cars#33]
**Andres**
- [x] `Makefile` draft
- [x] Readme / usage updates
- [x] Update wrangling script to run with default parameters from root directory

**Braden**
- [x] Automate embedding model accuracies in the report
- [x] Make the images render in the report

**Serg**
- [x] `Makefile` cleanup / finalize
- [x] Update report with latest machine learning results
- [x] Update test model script to store models accuracies / results (for the report)
- [x] Update machine learning scripts to run with default parameters from root directory

**Upcoming / To be assigned**
- [x] TA Feedback
- [ ] Lab feedback

**Comment by pokrovskyy** [comment]
Made some adjustments here - looks like we're on the right track to NOT commit everything in the last minute? :) I think there is some feedback to be addressed regarding the final report that we could collectively work during the day, if you have time.
