### ISSUE TITLE
Milestone 4 tasks

### ISSUE THREAD

**Issue by pokrovskyy** [UBC-MDS/DSCI_522_Group-308_Used-Cars#60]
So far we have this for Milestone 4:

- [x] Kate's feedback:
  - [x] #53 
  - [x] #54
  - [x] #55 
  - [x] #56 
  - [x] #57

- [x] Firas feedback #52
- [x] Docker build
  - [x] EDA / Selenium
  - [x] Reports generation / knitting
- [x] Finalize & cleanup everything we know / care about
- [x] Final image deployment
- [x] Makefile png

Feel free to add / comment stuff here!

**Comment by AndresPitta** [comment]
Hey,
I already corrected the EDA and added a partial_clean section to the makefile. Also, added a dependecy so that in the graph test_results_sample.csv depends on model.pic (but I made the partial clean so that it does not delete the test_results_sample.csv, and everytime we run the quick version we just run the quick model)
